# Generated by Django 4.0.2 on 2022-02-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_id', models.TextField()),
                ('e_name', models.TextField(max_length=200)),
                ('e_age', models.IntegerField()),
            ],
            options={
                'db_table': 'employee_table',
            },
        ),
    ]
